CC = gcc

all: md5_test

md5_test: md5.o md5_test.o
	$(CC) -Wall $^ -o $@

md5_test.o: md5_test.c md5.h
	$(CC) -Wall -c $<

md5.o: md5.c md5.h
	$(CC) -Wall -c $<

clean:
	rm -f md5_test md5_test.o md5.o
